"use client";

import { AnimatePresence, motion } from "motion/react";
import { ChevronDown } from "lucide-react";
import { useEffect, useState } from "react";
import type { Recommendation } from "@/recommendations/types";
import { OpenInSpotify } from "@/components/brand/SpotifyIcon";
import { Artwork } from "@/components/ui/Artwork";
import { PageHeader, SectionLabel } from "@/components/ui/PageHeader";
import { ProvenanceTag } from "@/components/ui/ProvenanceTag";
import { EmptyState, ErrorState } from "@/components/ui/States";
import { artistNames, titleCase } from "@/lib/client/format";
import { useDiscovery } from "@/lib/client/queries";

const LANE: Record<Recommendation["lane"], string> = {
  genre: "Genre match",
  "adjacent-artist": "Edge of your rotation",
  "new-release": "New from a favourite",
};

const STEPS = ["Reading your taste profile", "Searching the Spotify catalog", "Removing music you already know", "Scoring candidates"];

export function DiscoveryView() {
  const { data, error, isLoading, refetch } = useDiscovery();
  return (
    <div className="flex flex-col gap-12">
      <PageHeader
        eyebrow="Discovery"
        title={
          <>
            Music you are likely to <span className="font-serif font-normal italic">love</span>
          </>
        }
        aside={<ProvenanceTag kind="algorithm" label="Generated by this app — not by Spotify" />}
      >
        Candidates come from Spotify catalog search, seeded by your genres, the artists on the edge of your rotation and new releases
        from your favourites. This app then filters out what you already know and ranks the rest with a transparent score.
      </PageHeader>

      {isLoading ? (
        <Building />
      ) : error ? (
        <ErrorState error={error} onRetry={() => refetch()} compact />
      ) : !data || data.recommendations.length === 0 ? (
        <EmptyState title="No recommendations yet">
          There is not enough taste signal (top genres or artists) to search for candidates. As Spotify builds your top lists, this
          page fills itself.
        </EmptyState>
      ) : (
        <>
          <section className="grid gap-8 border-y border-line py-8 md:grid-cols-3">
            <div>
              <p className="eyebrow">Your genres</p>
              <p className="mt-3 text-sm leading-relaxed text-fg-2">
                {data.taste.genres.length ? data.taste.genres.slice(0, 5).map((g) => titleCase(g.name)).join(" · ") : "No genre tags available"}
              </p>
            </div>
            <div>
              <p className="eyebrow">Core artists</p>
              <p className="mt-3 text-sm leading-relaxed text-fg-2">{data.taste.coreArtists.slice(0, 5).map((a) => a.name).join(" · ")}</p>
            </div>
            <div>
              <p className="eyebrow">Era</p>
              <p className="mt-3 text-sm leading-relaxed text-fg-2">
                {data.taste.era ? `Most favourites released ${data.taste.era.from}–${data.taste.era.to}` : "Not enough release dates"}
              </p>
            </div>
          </section>

          <section>
            <SectionLabel right={<span className="font-mono text-[10px] text-faint">{data.stats.candidates} candidates · {data.stats.filteredKnown} already known</span>}>
              Ranked for you
            </SectionLabel>
            <ol className="flex flex-col">
              {data.recommendations.map((r, i) => (
                <RecCard key={r.track.id} rec={r} index={i} />
              ))}
            </ol>
          </section>

          <Method />
        </>
      )}
    </div>
  );
}

function Building() {
  const [step, setStep] = useState(0);
  useEffect(() => {
    const id = setInterval(() => setStep((s) => Math.min(STEPS.length - 1, s + 1)), 1400);
    return () => clearInterval(id);
  }, []);
  return (
    <div className="py-16" role="status" aria-live="polite">
      <p className="eyebrow">Building candidates</p>
      <div className="mt-4 h-[1.2em] overflow-hidden text-3xl font-semibold tracking-tight">
        <AnimatePresence mode="popLayout">
          <motion.p key={step} initial={{ y: "100%" }} animate={{ y: 0 }} exit={{ y: "-100%" }} transition={{ duration: 0.5, ease: [0.16, 1, 0.3, 1] }}>
            {STEPS[step]}…
          </motion.p>
        </AnimatePresence>
      </div>
      <div className="mt-8 flex max-w-md gap-[3px]">
        {Array.from({ length: 24 }, (_, i) => (
          <motion.span key={i} className="h-2.5 flex-1 rounded-[1px] bg-white/10" animate={{ backgroundColor: ["rgba(255,255,255,0.08)", "var(--accent)", "rgba(255,255,255,0.08)"] }} transition={{ duration: 1.6, repeat: Infinity, delay: i * 0.06 }} />
        ))}
      </div>
    </div>
  );
}

function RecCard({ rec, index }: { rec: Recommendation; index: number }) {
  const [open, setOpen] = useState(index < 3);
  return (
    <motion.li
      className="border-b border-line"
      initial={{ opacity: 0, y: 16 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, margin: "-5%" }}
      transition={{ duration: 0.6, ease: [0.16, 1, 0.3, 1], delay: Math.min(index, 6) * 0.05 }}
    >
      <div className="grid grid-cols-[auto_1fr_auto] items-center gap-4 py-4 sm:gap-6">
        <Artwork images={rec.track.album.images} alt={rec.track.album.name} size={72} />
        <button onClick={() => setOpen((o) => !o)} className="min-w-0 text-left" aria-expanded={open}>
          <p className="font-mono text-[10px] tracking-[0.14em] text-algorithm uppercase">{LANE[rec.lane]}</p>
          <p className="mt-1 truncate text-lg font-semibold tracking-tight">{rec.track.name}</p>
          <p className="truncate text-sm text-muted">
            {artistNames(rec.track.artists)}
            {rec.track.album.releaseYear ? ` · ${rec.track.album.releaseYear}` : ""}
          </p>
        </button>
        <div className="flex items-center gap-3">
          <ScoreRing score={rec.score} />
          <OpenInSpotify href={rec.track.url} compact />
          <button onClick={() => setOpen((o) => !o)} aria-label={open ? "Hide reasons" : "Show reasons"} className="hidden rounded-full p-1.5 text-muted hover:text-fg sm:block">
            <ChevronDown className={`size-4 transition ${open ? "rotate-180" : ""}`} />
          </button>
        </div>
      </div>
      <AnimatePresence initial={false}>
        {open && (
          <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: "auto", opacity: 1 }} exit={{ height: 0, opacity: 0 }} transition={{ duration: 0.4, ease: [0.16, 1, 0.3, 1] }} className="overflow-hidden">
            <div className="grid gap-6 pb-6 sm:grid-cols-[1fr_260px] sm:pl-[96px]">
              <div>
                <p className="eyebrow">Why you might like this</p>
                <ul className="mt-3 flex flex-col gap-2 text-sm text-fg-2">
                  {rec.reasons.map((r) => (
                    <li key={r} className="flex gap-3">
                      <span className="mt-2 size-1 shrink-0 rounded-full bg-algorithm" />
                      {r}
                    </li>
                  ))}
                </ul>
              </div>
              <dl className="grid grid-cols-2 gap-x-4 gap-y-2 font-mono text-[11px]">
                {(
                  [
                    ["Genre match", rec.components.genreMatch],
                    ["Novelty", rec.components.novelty],
                    ["Era match", rec.components.eraMatch],
                    ["Source", rec.components.laneConfidence],
                  ] as const
                ).map(([k, v]) => (
                  <div key={k}>
                    <dt className="text-faint">{k}</dt>
                    <dd className="mt-1 flex items-center gap-2">
                      <span className="h-[3px] flex-1 overflow-hidden rounded-full bg-white/10">
                        <span className="block h-full bg-algorithm" style={{ width: `${Math.round(v * 100)}%` }} />
                      </span>
                      <span className="w-7 text-right text-fg-2">{Math.round(v * 100)}</span>
                    </dd>
                  </div>
                ))}
              </dl>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.li>
  );
}

function ScoreRing({ score }: { score: number }) {
  const r = 17;
  const c = 2 * Math.PI * r;
  return (
    <div className="relative grid size-11 place-items-center" title={`Score ${score}/100`}>
      <svg viewBox="0 0 44 44" className="absolute inset-0 -rotate-90">
        <circle cx="22" cy="22" r={r} fill="none" stroke="rgba(255,255,255,0.08)" strokeWidth="2" />
        <motion.circle cx="22" cy="22" r={r} fill="none" stroke="var(--color-algorithm)" strokeWidth="2" strokeLinecap="round" strokeDasharray={c} initial={{ strokeDashoffset: c }} whileInView={{ strokeDashoffset: c * (1 - score / 100) }} viewport={{ once: true }} transition={{ duration: 1.2, ease: [0.16, 1, 0.3, 1] }} />
      </svg>
      <span className="numeric text-xs">{score}</span>
    </div>
  );
}

function Method() {
  return (
    <details className="group border-t border-line pt-5">
      <summary className="flex cursor-pointer list-none items-center justify-between">
        <span className="eyebrow">How recommendations are scored</span>
        <ChevronDown className="size-4 text-muted transition group-open:rotate-180" />
      </summary>
      <div className="mt-4 grid max-w-3xl gap-3 text-sm leading-relaxed text-fg-2">
        <p>
          Score = 45% genre match (candidate artist&apos;s Spotify genres weighted by your genre shares) + 30% novelty (new artist = full
          points, an artist near your rotation = partial) + 15% era match (release year vs. the years most of your favourites come
          from) + 10% source confidence.
        </p>
        <p>At most two tracks per artist are kept, and anything already in your top lists, recent plays or analysed library is removed.</p>
        <p className="text-muted">
          Spotify&apos;s own recommendation, related-artist and audio-feature endpoints are not available to new apps, so none of them
          are used.
        </p>
      </div>
    </details>
  );
}
